var express = require("express");
var cors = require('cors')
var app = express();

app.listen(8080, () => {
    console.log("Server running on port 8080");
});

app.get("/phones", cors(), (req, res, next) => {
    res.json([
        {
            "id": 1,
            "title": "iPhone 7",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has 1234567",
            "color": "black",
            "price": "200$",
            "stars": "23",
            "image": "https://media.istockphoto.com/photos/front-view-of-gold-apple-iphone-6s-mockup-with-black-screen-isolated-picture-id827862890",
        },
        {
            "id": 2,
            "title": "Samsung S7",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "black, white",
            "price": "500$",
            "stars": "75",
            "image": "https://images.pexels.com/photos/248512/pexels-photo-248512.jpeg",
        },
        {
            "id": 3,
            "title": "Samsung A5",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "white",
            "price": "100$",
            "stars": "12",
            "image": "https://images.pexels.com/photos/248512/pexels-photo-248512.jpeg",
        },
        {
            "id": 4,
            "title": "iPhone 10",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "red",
            "price": "1$",
            "stars": "75",
            "image": "https://media.istockphoto.com/photos/front-view-of-gold-apple-iphone-6s-mockup-with-black-screen-isolated-picture-id827862890",
        },
        {
            "id": 5,
            "title": "iPhone 11",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "white",
            "price": "1$",
            "stars": "100",
            "image": "https://images.pexels.com/photos/248512/pexels-photo-248512.jpeg",
        },
        {
            "id": 6,
            "title": "iPhone 12",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "white, black",
            "price": "1000$",
            "stars": "99",
            "image": "https://media.istockphoto.com/photos/front-view-of-gold-apple-iphone-6s-mockup-with-black-screen-isolated-picture-id827862890",
        },
        {
            "id": 7,
            "title": "iPhone 7",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has 1234567",
            "color": "black",
            "price": "200$",
            "stars": "23",
            "image": "https://media.istockphoto.com/photos/front-view-of-gold-apple-iphone-6s-mockup-with-black-screen-isolated-picture-id827862890",
        },
        {
            "id": 8,
            "title": "Samsung S7",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "black, white",
            "price": "500$",
            "stars": "75",
            "image": "https://images.pexels.com/photos/248512/pexels-photo-248512.jpeg",
        },
        {
            "id": 9,
            "title": "Samsung A5",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "white",
            "price": "100$",
            "stars": "12",
            "image": "https://images.pexels.com/photos/248512/pexels-photo-248512.jpeg",
        },
        {
            "id": 10,
            "title": "iPhone 10",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "red",
            "price": "1$",
            "stars": "75",
            "image": "https://media.istockphoto.com/photos/front-view-of-gold-apple-iphone-6s-mockup-with-black-screen-isolated-picture-id827862890",
        },
        {
            "id": 11,
            "title": "iPhone 11",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "white",
            "price": "1$",
            "stars": "100",
            "image": "https://images.pexels.com/photos/248512/pexels-photo-248512.jpeg",
        },
        {
            "id": 12,
            "title": "iPhone 12",
            "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has ",
            "color": "white, black",
            "price": "1000$",
            "stars": "99",
            "image": "https://media.istockphoto.com/photos/front-view-of-gold-apple-iphone-6s-mockup-with-black-screen-isolated-picture-id827862890",
        },
    ]);
});